# Generated by Django 5.0.3 on 2024-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates_title', models.CharField(max_length=200)),
                ('templates_description', models.TextField(blank=True, null=True)),
                ('templates_pic', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('templates_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_cover',
            field=models.ImageField(blank=True, default='upload/Default_cover.png', null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_pic',
            field=models.ImageField(blank=True, default='upload/Default_pic.png', null=True, upload_to='upload'),
        ),
    ]
