# Generated by Django 5.0.3 on 2024-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_templates_project_project_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_profile_cover',
            field=models.ImageField(blank=True, default='../upload/Default_cover.png', null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_pic',
            field=models.ImageField(blank=True, default='../upload/Default_pic.png', null=True, upload_to='upload'),
        ),
    ]
